sudo: required
services:
  - docker

before_install:
  - docker build -t abassadey/react-test -f ./client/Dockerfile.dev ./

script:
  - docker run -e CI=true abassadey/react-test npm test

after_success:
  - docker build -t abassadey/multi-client ./client
  - docker build -t abassadey/multi-nginx ./nginx
  - docker build -t abassadey/multi-server ./server
  - docker build -t abassadey/multi-worker ./worker
  # Log in to docker cli with credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abassadey/multi-client
  - docker push abassadey/multi-nginx
  - docker push abassadey/multi-server
  - docker push abassadey/multi-worker
